# Настройки STT (Vosk)
stt:
  model_path: "models/vosk-model-ru-0.22"
  sample_rate: 16000

# Настройки нейросети (LM Studio)
ai:
  api_url: "http://localhost:1234/v1/chat/completions"
  default_params:
    temperature: 0.5  # Уменьшаем случайность
    max_tokens: 128   # Увеличиваем лимит генерации
    top_p: 0.9
    frequency_penalty: 0.5  # Штраф за повторения
    presence_penalty: 0.9    # Поощрение новых тем
    num_ctx: 2048      # Размер контекстного окна

# Персонажи
personalities:
  - name: "clown"
    system_prompt: |
      [Инструкция]
      Анализируй контекст 10 секунд перед ответом
      Говори только на русском языке и покороче, 
      желательно, но не обязательно писать сообщения до 50 символов. 
      Не используй знаки пунктуации, как междометия используй "Бля" "ёпта" "братан", 
      но при этом не опускайся до уровня тюремного жаргона.
    response_params:
      temperature: 1.3
      max_tokens: 128
      top_p: 0.9

  - name: "gopota"
    system_prompt: |
      [Инструкция]
      Анализируй контекст 10 секунд перед ответом
      Говори только на русском языке и покороче, 
      желательно, но не обязательно писать сообщения до 50 символов. 
      Не используй знаки пунктуации, как междометия используй "Бля" "ёпта" "братан", 
      но при этом не опускайся до уровня тюремного жаргона.
    response_params:
      temperature: 1.4
      max_tokens: 128
      top_p: 0.85

# Аккаунты Twitch
accounts:
  - username: "ZHABBIX"
    oauth: ${ZHABBIX_OAUTH}
    channel: "#ayayazen"
    personality: "clown"

  - username: "BURMALDINO"
    oauth: ${BURMALDINO_OAUTH}
    channel: "#ayayazen"
    personality: "clown"

  - username: "pipd"
    oauth: ${PIPD_OAUTH}
    channel: "#ayayazen"
    personality: "gopota"