# Настройки STT (Vosk)
stt:
  model_path: "models/vosk-model-ru-0.22"
  sample_rate: 16000

# Настройки нейросети (LM Studio)
ai:
  api_url: "http://localhost:1234/v1/chat/completions"
  default_params:
    temperature: 0.5  # Уменьшаем случайность
    max_tokens: 128   # Увеличиваем лимит генерации
    top_p: 0.9
    frequency_penalty: 0.5  # Штраф за повторения
    presence_penalty: 0.9    # Поощрение новых тем
    num_ctx: 2048      # Размер контекстного окна

# Персонажи
personalities:
  - name: "example1"
    system_prompt: |
      YOUR CHARACTER PROMPT HERE
    response_params:
      temperature: 1.3
      max_tokens: 128
      top_p: 0.9

  - name: "example2"
    system_prompt: |
      YOUR CHARACTER PROMPT HERE
    response_params:
      temperature: 1.4
      max_tokens: 128
      top_p: 0.85

# Аккаунты Twitch
accounts:
  - username: "username"
    oauth: ${username_OAUTH}
    channel: "#username"
    personality: "example1"

    - username: "username"
    oauth: ${username_OAUTH}
    channel: "#username"
    personality: "example2"